### ISSUE TITLE
Use gltf 2.0 for the mesh instead of escn

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3d-mannequin#13]
/!\ Export from Blender 2.81+ and import in Godot 3.2+.

**Comment by AndreaMonzini** [comment]
Hello, 
where i can find the .blend file ?
thank you for the project!

**Comment by NathanLovato** [comment]
Hi @AndreaMonzini, the blend file is distributed in the releases tab: https://github.com/GDquest/godot-3d-mannequin/releases
I've been working on this, it mostly works, but the jump animation's frames 12, 13, and 14 are bugged after export (regardless of the exporter, same issue with escn, gltf, and fbx)

![Screenshot from 2019-11-21 19-45-56](https://user-images.githubusercontent.com/12694995/69480103-a50d6d00-0e04-11ea-97f3-273f43e08f3f.png)

![Screenshot from 2019-11-21 20-17-02](https://user-images.githubusercontent.com/12694995/69480113-ae96d500-0e04-11ea-8df1-1f6d8da47738.png)

If you know how to fix it your help would be most welcome!

**Comment by AndreaMonzini** [comment]
i am trying to export the animation with gltf ( .glb )  but it doesn't work for now

**Comment by julienduroure** [comment]
Not linked to KhronosGroup/glTF-Blender-IO#765, here rest pose is OK. Will have a look

**Comment by julienduroure** [comment]
@NathanLovato 
Seems to be linked to scale near to 0 of deformation bone DEF-spine.002 during the jump.
Tweaking the bone tweak_spine.002 (to avoid this near to 0 scaling) seems to solve the issue

**Comment by NathanLovato** [comment]
Thanks a lot @julienduroure 🙂

**Comment by AndreaMonzini** [comment]
> Not linked to [KhronosGroup/glTF-Blender-IO#765](https://github.com/KhronosGroup/glTF-Blender-IO/issues/765), here rest pose is OK. Will have a look

it was just  referred to the title issue" glTF2 Export Error Mannequin ", anyway i wanted to point to the right place to report gltf export problems :

https://github.com/KhronosGroup/glTF-Blender-IO

Thank you for your work :)

**Comment by NathanLovato** [comment]
Done with 7459dbaa6579d1ee06dae412f43f7a4f70e4865b
