### ISSUE TITLE
Can't open the project

### ISSUE THREAD

**Issue by ciction** [GDQuest/godot-3d-mannequin#24]
Hi, 
I downloaded the project and imported it in Godot v3.2.1.

There seems to be something wrong with the dependencies in Mannequiny.tscn.
I can't open or run the project at all on windows.

![image](https://user-images.githubusercontent.com/7746507/71321711-ec4b5400-24bd-11ea-98a2-54ab7d221345.png)

**Comment by NathanLovato** [comment]
There's no Godot 3.2.1 out yet. Are you using Godot 3.1.1 instead? If so, it's normal: you need Godot 3.2 beta at least to open the project: https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4

**Comment by dirkk0** [comment]
I can confirm that it works on Mac OSX; great work, thank you!

**Comment by bitmammoth** [comment]
> I can confirm that it works on Mac OSX; great work, thank you!

win 10 and linux 19.10 as well
