### ISSUE TITLE
Godot 3.2 release exception

### ISSUE THREAD

**Issue by pcholt** [GDQuest/godot-3d-mannequin#29]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Version: v0.2.0, as provided on the template list available with the latest godot 3.2 download, exits with exception when run from the editor.

    State.gd:18
    Trying to assign value of type 'StateMachine.gd' to a variable of type 'State.gd'.

**What is the expected behavior?**
Not exiting with an exception, I would imagine.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
Immediate exception.
1. Run in the UI
2. Immediate exception will be apparent

**Comment by NathanLovato** [comment]
It's already fixed, I'll release v0.3.0 in a moment.

**Comment by NathanLovato** [comment]
Thanks for the report!
