### ISSUE TITLE
Memory leakage in project, even in editor

### ISSUE THREAD

**Issue by qarmin** [GDQuest/godot-3d-mannequin#30]
- [x] Bug report.
- [ ] Feature request.

## Bug report ##

When I open project(even in editor) and close it, then I see leak:
```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476.
```
When I add -v argument to Godot run command, then I see that `res://src/Main/StateMachine/State.gd` leaks
```
Orphan StringName: msg
Orphan StringName: owner
Orphan StringName: unhandled_input
Orphan StringName: GDScriptNativeClass
Orphan StringName: is_in_group
Orphan StringName: node
Orphan StringName: res://src/Main/StateMachine/State.gd
Orphan StringName: enter
Orphan StringName: _parent
Orphan StringName: _state_machine
Orphan StringName: _get_state_machine
Orphan StringName: get_parent
Orphan StringName: Node
Orphan StringName: InputEvent
Orphan StringName: event
Orphan StringName: physics_process
Orphan StringName: _init
Orphan StringName: _ready
Orphan StringName: exit
Orphan StringName: GDScript
Orphan StringName: delta
Orphan StringName: process
```
I'm not sure  what cause leaks, but probably returning inside class, objects of this class or parent class.

**Comment by NathanLovato** [comment]
Thanks. I don't know what would be causing this. It's just a virtual class, it doesn't run in the editor (i.e. it's not using tool mode) and as users, we're not managing memory. Do you have a more precise idea of what could be causing that?

**Comment by qarmin** [comment]
Seems that leak happens in this line
https://github.com/GDQuest/godot-3d-mannequin/blob/e34df30e431e9d11d099e64a1a84742de43844d0/src/Main/StateMachine/State.gd#L11
and this is almost same bug as https://github.com/godotengine/godot/issues/30668

as workaround I suggest to remove all information's about types, where type of variable is same as class in which is(until of course the bug is fixed in Godot).
Changing line from above to:
```
var _parent = null 
```
fixes leak.

**Comment by NathanLovato** [comment]
Thanks!
