### ISSUE TITLE
Add interpolation to the facing direction when moving

### ISSUE THREAD

**Issue by FelixNemis** [GDQuest/godot-3d-mannequin#31]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Feature request ##

**Add interpolation to the player's angle instead of immediately snapping to the move direction**

I think the character controller is much more appealing when a bit of interpolation is added to the angle changing as the character moves around. Especially when using digital controls like a keyboard or dpad, the robotic looking snap as the character turns looks jarring.

I gave it a shot myself and recorded a [quick video](https://www.youtube.com/watch?v=BGg_KQH4ZjQ)

This was where I added the interpolation
![Selection_381](https://user-images.githubusercontent.com/6477924/73969997-044a2c00-48e2-11ea-8e10-b86bd489a60f.png)

**Comment by ee0pdt** [comment]
@FelixNemis if you've got a working solution I suggest you raise a Pull Request instead of an issue.
