### ISSUE TITLE
Towards more open source prototype assets

### ISSUE THREAD

**Issue by Nodragem** [GDQuest/godot-3d-mannequin#33]
I think the 3D mannequin is a super nice idea!
This morning I saw this package on Humble bundle:
https://youtu.be/KAiun66iyBA

And I thought, hey, why not doing a open source bundle of prototype assets? :D Looking at the number of assets in the pack above, it could be a community effort, and we might need to get some organisation around it. But I think it could be a thing!

The 3D mannequin is a step towards this and so I thought it would be nice to contact you, to see what you think about it.

**Comment by NathanLovato** [comment]
I've seen some attempts before, a lot of hype from users, but no contributors to make it happen. In my experience, this doesn't happen without a budget and/or one fully dedicated artist, like the person behind https://texturehaven.com/ and https://hdrihaven.com/

**Comment by Megalomaniak** [comment]
Yes, what @NathanLovato said. I've wanted to do something like this before, but it's rather demotivational to work towards something like this alone, especially with no funding.

On that note tho, @NathanLovato any chance of the character/rigs blend file being shared so we could more easily build assets around it? Or is it already available somewhere and I've missed it?

**Comment by NathanLovato** [comment]
Mannequiny is already available for download along with the releases: https://github.com/GDQuest/godot-3d-mannequin/releases/

Coming back to the topic, to me, working alone wouldn't be a problem for me. But you have to understand that out of tens of thousands of people following you, you get but a handful of contributors. And you get way more persons who message you saying they'll do something, take your time with discussions, and never act upon it. I can tell you that from experience.

So I don't believe this can be a community effort, even if you have a few content creators to drive the project. Having everyone adapt to the art style takes some investment, and while devs are used to working with other people's code, to the idea of sharing with the sheer amount of Free Software available out there, and having to adapt to a given codebase, that's not necessarily the case with artists.

Professionals, who work in teams, of course, can, but none of these pros around me have time. Unless you pay them.

Anyway, we're already working towards making more FOSS prototype assets. For example, all the sprites from our [game art style guide](https://www.gdquest.com/docs/guidelines/style-guides/game-art/) are vector and FOSS. And pretty much all our art is CC-By 4.0.

**Comment by Megalomaniak** [comment]
Yeah, I mean if it's meant to be community effort then I think it is demotivational to end up being the only one doing the work whereas just as you said, there's usually a whole bunch of people promising to contribute. Same experience here.

Probably easier to do something similar to how the mod packs tend to be created for the elder scrolls games.

Someone aggregates mods they like and think fit together well into a pack where all the potential dependency issues have been worked out. Except in this case, it would be someone cherry-picking assets from say opengameart.org and tweaking them all to fit together in a pack.

I could see that working, maybe.

**Comment by NathanLovato** [comment]
> Except in this case, it would be someone cherry-picking assets from say opengameart.org and tweaking them all to fit together in a pack.

This won't work to me as you need assets to match in terms of style, scale, etc. and few do on platforms like these. You really need to work out art guidelines and to create the assets to spec for this to happen.

I'd like us to do something like that sometime. I just need to find a 3D game artist who uses Blender to work with, who could match our budget, scope, and workflow, i.e. make simple, but well-designed 3D art, and accept that we directly work with and share the source files. So I'd need a pretty mature artist there.

**Comment by Megalomaniak** [comment]
Well, depends. For more stylized designs this is definitely true, but for asset packs going for more photo-real environment assets, it mostly comes down to scaling assets and making sure the texel scale matches reasonably well as well. Especially considering that photoscanning is much more common now.

For much more complex assets such as characters and weapons and such though, yeah. Generic assets even if they are well made wouldn't be a very good fit anyways. They'd still need to be catered custom for each specific game project.

**Comment by NathanLovato** [comment]
Yup.

For now, I'll close the issue as we're not going to start such a project, and as it's not related to Mannequiny.

**Comment by Nodragem** [comment]
yes, I knew it was only slightly related to Mannequiny, but I am happy we started this discussion :) it gave us some insights on what would be the challenges, the constraints, and who else is interested! Hopefully we can discuss further on discord/email :)
