### ISSUE TITLE
CameraRig.tscn changes unexpectedly in filesystem based on property updates

### ISSUE THREAD

**Issue by hammerandtongs** [GDQuest/godot-3d-mannequin#34]
**I'm submitting a...**

- [ x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

src/Player/Camera/CameraRig.tscn
thrashes on the filesystem

```
-length_range = Vector2( 3, 6 )
-zoom = 0.5

```
then it will be added to the tscn file after using the editor, running the game again.

**What is the expected behavior?**

It's unexpected that the tscn would change just based on using the editor and running the game without editor changes.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Using git underneath the project reveals this quickly.

My assumption is that this is an issue with using "tool" in the SpringArm.gd source file?

**Comment by NathanLovato** [comment]
It's not due to this project specifically, it's due to saving. When you save a scene, Godot serializes it fresh, so sometimes you have small artefacts or changes in version control.

I reckon this does not affect the game at runtime, right? If so, it's not a bug

**Comment by hammerandtongs** [comment]
adding -

+       if not Engine.editor_hint:
+               zoom = clamp(value, 0.0, 1.0)
+               spring_arm.zoom = zoom

In the set_zoom function seems to fix it so far. I think set_zoom is firing because of the setget on it and tool keyword?

https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html#what-is-tool

**Comment by NathanLovato** [comment]
Which version of Godot are you using? I cannot reproduce your issue with Godot 3.2 stable.

**Comment by NathanLovato** [comment]
Note that as I said above, it looks like a Godot serialization issue. If the values of the camera's exported properties don't change, the serialized scene shouldn't change either. Tool mode or not, it's not related.

However, I just made a change to only set the zoom value when the spring arm is ready. Could you download the latest master and see if the issue is still there?

**Comment by NathanLovato** [comment]
Also, setter functions should pretty much always assign the value to the property, included in the editor. Otherwise, you will prevent the user from changing [exported] values.

**Comment by hammerandtongs** [comment]
I'm on v3.2.stable.flathub Ubuntu 18.04

Thanks, I'll try your CameraRig.gd changes for a bit. 

As I recall from your tutorials that the "tool" is only there to trigger warnings if there is no proper parent?

**Comment by hammerandtongs** [comment]
Not able to find a consistent repro for this despite it plaguing me for days.

I'll reopen if I can find one, thanks for the help and the great tutorial!
