### ISSUE TITLE
CAMERA: Camera y inversion can't be toggled by pressing the intended input during gameplay

### ISSUE THREAD

**Issue by HeroFoxtrot** [GDQuest/godot-3d-mannequin#35]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Camera y rotation stays the same after pressing the intended input (default input = Control+Y).

**What is the expected behavior?**
Camera y rotation become inverted after pressing the intended input (default input = Control+Y).

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
1. Click Play button or (F5)
2. Observe the camera y roation as the user move the mouse back and forth
3. Try to enable the camera y inversion with [Control+Y]
4. Observe the camera y roation again as the user move the mouse back and forth

## Other ##

**Other information**
This issue was found on release v0.3.0
The camera y inversion action (toggle_y_inversion) from the input map settings does not seems to be called in any function. For a temporary fix, I added those following lines of code in the **Camera.gd** script under **unhandled_input(event)**:

	if event.is_action_pressed("toggle_y_inversion") and is_y_inverted == false:
		is_y_inverted = true
	elif event.is_action_pressed("toggle_y_inversion") and is_y_inverted == true:
		is_y_inverted = false

**Comment by NathanLovato** [comment]
Thanks, note you can write boolean toggles like this:
```gdscript
if event.is_action_pressed("toggle_y_inversion"):
	is_y_inverted = not is_y_inverted
```

**Comment by HeroFoxtrot** [comment]
Thanks for the tips, I'm not the greatest at writing codes, I still consider myself a novice .

**Comment by NathanLovato** [comment]
Actually I had just forgotten to remove the input action, it shouldn't exist. That's fixed.
