### ISSUE TITLE
Character movement

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3d-mannequin#4]
I don't have precise requirements for the character's movement yet as we need a prototype first. We can do some back-and-forth to get the feel right.

The character should support platform and action. I'd use Zelda games as a reference:

- BotW: https://www.youtube.com/watch?v=r2JtSXXY_WY (same video as in #3 )
- The Wind Waker: https://youtu.be/2xnA9tAqaUg?t=727

## Technical constraints

The character should use root motion for ground movement.

**Comment by Cheeseness** [comment]
I've got something that feels like it's getting close to a good starting point for ground movement (forward/backward/left/right) over in the https://github.com/GDquest/godot-3d-mannequin/tree/movement-experiments branch.

Would love some thoughts/feedback on general feel as well as code style!

Jumping is still pretty rudimentary, and I haven't yet looked at other movement styles/mechanics such as rolling, crawling, ledge grab, hookshot, etc.

**Comment by NathanLovato** [comment]
I'll test this right away. In general, you can open a draft PR from your branch, this way I can use hub to instantly get and test everything

**Comment by Cheeseness** [comment]
Sure thing - I figured a quick playtest for initial feel as a sanity check before opening a first PR was probably a good idea.

**Comment by NathanLovato** [comment]
Just tested it, nice start. Looking at the code, I'd like to change the style, especially remove nested if blocks or things like mixed camel and snake case for identifiers.

**Comment by Cheeseness** [comment]
Thanks! I'll open a pull request for proper review.

**Comment by NathanLovato** [comment]
If the code is ready, can you check the box so I can commit directly to your branch? Reviewing line by line would take too much time in comparison, it's easier for me to show than explain our style, esp. if you're used to writing imperative code that way

**Comment by Cheeseness** [comment]
I don't see the settings button shown on (this page)[https://help.github.com/en/articles/enabling-branch-restrictions]. Is there another way to toggle that?

**Comment by Cheeseness** [comment]
@NathanLovato  Had a bit more of a look around, but still haven't been able to find a relevant checkbox for allowing reviewer commits or any branch restrictions. Are you sure you don't have push permissions across the entire repository?

In the meantime, I've added c3ee551 to attempt to address style oversights that I've spotted.

**Comment by NathanLovato** [comment]
I forgot you were directly working on a branch on this repo, I have write access to it. I have to work on the next course release in priority, this can wait as it's just code cleanup - you can keep going
