### ISSUE TITLE
Mannequin does not show up in the Editor built-in AssetLib browser

### ISSUE THREAD

**Issue by golddotasksquestions** [GDQuest/godot-3d-mannequin#47]
**I'm submitting a...**

- [x ] Bug report?
- [ x] Feature request?

## Bug report ##

**What is the current behavior?**
[Despite it being available in the Asset Library](https://godotengine.org/asset-library/asset/440), it's not available in the Godot AssetLib browser in Godot 3.5.1 or earlier.

Search prompts I have tried: "Mannequin", "Mannequiny", "GDQuest"

**What is the expected behavior?**
Have it show up in a convenient AssetLib search.

PS: It would also be nice if the .blend file could be included in the download. This would make it easier to edit or add animations and change the mesh (for different proportions or body type for example. Someone who downloads the mannequin via AssetLib won't be aware of the availability of the .blend file in the Github releases. Even though I checked the Github page many times before, I only now realised there is a .blend file available when I was reading through some of the other issues here.

**Comment by Calinou** [comment]
This is because the asset's version is still listed as 3.2 on the asset library. Does this project work correctly on 3.5? If so, I can update its version on the asset library.

**Comment by NathanLovato** [comment]
I just tested it in Godot 3.5 and everything seems to be running fine. If you don't mind making the change @Calinou it'd be most welcome as my plate's constantly full.

> PS: It would also be nice if the .blend file could be included in the download

Agreed. It's part of the things where we don't find the time to code script to properly automate the publication of source assets, and we need that, we have too much stuff to do things by hand. We need that or people who'd like to step up as maintainers.

The blend file's included in the latest release on Github by the way, here's the link: https://github.com/GDQuest/godot-3d-mannequin/releases/download/v0.4.0/mannequiny-0.4.0.blend

**Comment by Calinou** [comment]
> If you don't mind making the change @Calinou it'd be most welcome as my plate's constantly full.

Done :slightly_smiling_face: 

This issue can be closed now.

**Comment by NathanLovato** [comment]
Thanks much Hugo!
