### ISSUE TITLE
Using Rig On the Fly addon is a mistake

### ISSUE THREAD

**Issue by enbugger** [GDQuest/godot-3d-mannequin#49]
The primary use case, due to which I found this repo, is that I wanted to have Godot-ready characters and ability to alter/add animations in Blender.

The project became less useful with removal of built-in rig in Blender file. I would say it makes the blend file useless as it is no different to simple gltf file. One import gltf and get the identical blender project. 

Meanwhile, the addon which is recommended for usage is stuck on blender 2.x version and apparently was abandoned, making the suggested animating approach useless for Blender versions 3.x and 4.x

**Comment by NathanLovato** [comment]
Blender 2.90 and versions compatible with Rig on the Fly are still available! If you'd like to update the animations of this character, you could use that. You could also use the plug-in to make the rig you want, with IKs for example, save the file, and then open it in more recent versions of blender to keep working on it.

I hope this helps!
